# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: pyreqs-test
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Dependencies
      run: go get .
      
    - name: Test
      run: go test -v ./...

    - name: Build
      run: env GOOS="linux" GOARCH="arm64" go build -o pyreqs-linux . 

    - uses: actions/upload-artifact@v3
      with:
        name: pyreqs-linux
        path: pyreqs-linux

  release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        
      needs: build

      steps: 
        - uses: actions/download-artifact@v3
          with:
            name: pyreqs-linux
            path: build
        # - run: zip -r build.zip build/
        - uses: ncipollo/release-action@v1
          with:
            tag: v1.0.1
            artifacts: build/
